### ISSUE TITLE
cannot see the "circle" icon on the top bar.

### ISSUE THREAD

**Issue by FrancescoJacovo** [nextcloud/circles#1267]
I'm using it related to the "Collective" app version 25.0.0 and it works fine for that. But i cannot access to the specific app standalone

**Comment by onny** [comment]
Looks like in recent versions of Nextcloud, circles has been integrated into the contacts app. See this screenshot

![image](https://github.com/nextcloud/circles/assets/757752/9a462e94-667e-42a7-891f-c7fb4ec8860b)

Seems to be that case since Nextcloud 22 https://nextcloud.com/blog/nextcloud-hub-22-introduces-approval-workflows-integrated-knowledge-management-and-decentralized-group-administration/

**Comment by delacosta456** [comment]
hi 
 I am having this issue too on NC26.0.3

**Comment by mejo-** [comment]
As mentioned by @onny, the circles app doesn't have its own frontend anymore. You can manage your circles in the contacts app.
