### ISSUE TITLE
Unable to delete team that was created by collective

### ISSUE THREAD

**Issue by andynameistaken** [nextcloud/circles#1663]
Teams version: 29.0.0-dev

## Steps To Reproduce
- create a collective
- remove a collective
- go to the contacts app
- delete team that was created with a collective

## What happens
 message "Unable to delete team {circleId} and team is not deleted

## What should happen
Team should be deleted

**Comment by andynameistaken** [comment]
It seems that Team from Collective is not moved to trash as I don't see this option at the bottom you speak of:
<img width="231" alt="image" src="https://github.com/user-attachments/assets/69dd56b2-1465-4831-b3d8-a150e26eed63">

**Comment by mejo-** [comment]
Thanks for your report @andynameistaken. This is actually expected behaviour as deleting the team would silently delete the whole collective. That's why the team is marked as "app maintained" internally.

You can always delete the collective along with its team in the Collectives app. Be aware though that deleting a collective only marks it as "trashed" per default. You have to navigate to the collectives trash (at the bottom of the collectives list) and select "permanently delete collective" to really delete the collective along with its team.
