### ISSUE TITLE
'Add a Member'  function doesn't work

### ISSUE THREAD

**Issue by marco-bien** [nextcloud/circles#247]
When I want to add a member to a circle with the button right in the top of every circle regardless of circle type, I can Browse to the list of fitting user names after starting to type a name (autocomplete) but when I select one of them, nothing happens at all.

**nextcloud**
Version: 14.0.1.1
Apps installed: 51

**PHP**
Version: 7.2.7
Memory Limit: 512 MB
Max Execution Time: 3600
Upload max size: 511 MB

**Database**
Type: mysql
Version: 5.7.21
Size: 569.7 MB

testing with php 7.1 brings same error.

**Comment by daita** [comment]
Are you using the theming app ?

**Comment by marco-bien** [comment]
Yes, I'm using the theming app. Are there any incompatibilities?

**Comment by marco-bien** [comment]
> Yes, I'm using the theming app. Are there any incompatibilities?

OK, I can answer this for myself. Deactivating the theming app solves the problem, but I need/use the theming app for placing the policy and legal links because of GDPR policies ;-/

**Comment by marco-bien** [comment]
So is there any possibility to user both apps?

**Comment by daita** [comment]
i am working on this :)

**Comment by daita** [comment]
do you have any error in JS ? which version of Circles and Theming app are you using ?

**Comment by ferfebles** [comment]
Same problem here.

  Circles: 0.14.3
  Theming: 1.4.5

Even with Theming disabled I can't add users to a circle. After restarting php-fpm and reloading the browsers it works. Now I can add users.

Enabling Theming again, and I can add users without problems!.

No special JS errors, just: Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src 'self'". But I see the same error whether Theming is enabled or not.

Keeping it disabled until this issue gets resolved.

We are trying out Nextcloud, say something if you need more information or want as to test something.

**Comment by GoetheG** [comment]
Any news here?

**Comment by daita** [comment]
It should be fixed in NC15

**Comment by chandapettie** [comment]
it's not fixed....

**Comment by joshtrichards** [comment]
No longer applicable. If you problems with the new UI today, open a new issue since it's entirely different. Thanks for the reports!
