### ISSUE TITLE
Sharees: display owner of circle

### ISSUE THREAD

**Issue by ArtificialOwl** [nextcloud/circles#30]
- display the owner of circle when sharing/searching

**Comment by daita** [comment]
right now, only the UID is returned, not the display name.

**Comment by fgsl** [comment]
Hi, @daita. I would like to understand this issue to help if is possible.

But in current version I don't see behavior described above, at least for use case that I executed.

I did these steps:

1) Created a closed circle
2) Invited users to it
3) Users accepted invitations
4) As owner of circle, I shared a file.
5) As one of other members of circle, I see the file and details shows "shared with you by" [name of owner].

Then, it seems to me that issue is solved. May you confirm that?

Thank you.
