### ISSUE TITLE
Server migration, Shares shared by Circles gone

### ISSUE THREAD

**Issue by teqqat** [nextcloud/circles#364]
Good morning,

we have encountered again a strange effect.

After migrating from our old CT to a new VM everything worked flawless, including updating to the latest 17.0.2-1 
All shares with circles are gone, which are thousands of different shares in our ecosystem, the circles are still there, just not the shares. A check in the postgresql database shows the data is also there, it seems they are just not processed - creating a new share with the same name as before shows a "Name already existant" error. So "duplicates" are not allowed, but the shares are not shown/working.

Did you encounter such problems or have a solution? Reestablishing all shares becomes a problem with out colleagues already...

Thank you, teqq

**Comment by joshtrichards** [comment]
Hi @teqqat - Hopefully you found a resolution through a different channel. I'm clearing out some old issues. I can't think of a good reason that you encountered this off-hand, but it was presumably some small detail about the data or config migration.

I'm going to close this out since it's been >4 years and there's not much actionable left at this point, given both time and significant code changes.
