### ISSUE TITLE
No version for Nextcloud 22 in apps store

### ISSUE THREAD

**Issue by JuniorJPDJ** [nextcloud/circles#840]
Cuz of that nextcloud shows a box near version upgrade which says app doesn't have version for 22.

**Comment by ASmith-** [comment]
Ok, many of the circles issues have gone entirely uncommented and unsolved. **When do the Circles Developers of this very popular, widely used Nextcloud Plug In expect to have a working Circles Plugin for Nextcloud 22.2.x installed users?**

**Comment by ya-d** [comment]
I'm no expert but since NC22 Circles is integrated as a core feature. The "app" / plugin should be updated and will continue to work on NC22. Your circles should be kept but are now accessible and managed from within the Contacts app. There is no separate Circles app anymore.  See [release announcement](https://nextcloud.com/blog/nextcloud-hub-22-introduces-approval-workflows-integrated-knowledge-management-and-decentralized-group-administration/). [Further details…](https://help.nextcloud.com/t/circles-for-nc22/119703)

<img width="546" alt="image" src="https://user-images.githubusercontent.com/30781876/142407163-0744c5d1-6ac3-4c43-8953-6ee69f85e369.png">

**Comment by JuniorJPDJ** [comment]
Closing it then. Thanks for help.
